name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 通过 SSH 登录服务器执行部署命令
      - name: Run Deployment Script on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            pm2 stop bioford-web
            cd /opt/bioford/oxtium-bioford-web/BioFord_front
            git pull origin main
            npm ci
            npm run build
            pm2 start serve --name "bioford-web" -- -s -l 3000 /opt/bioford/oxtium-bioford-web/BioFord_front/dist
